# https://neptune.ai

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: username/${call:os.path.basename,${oc.env:PROJECT_ROOT}} # default to using the name of the project folder
  # name: ""
  log_model_checkpoints: True
  prefix: ""
