defaults:
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau

_target_: lightning_hydra_template.models.mnist_module.MNISTLitModule

net:
  _target_: lightning_hydra_template.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss

metrics:
  _target_: torchmetrics.MetricCollection
  # since MetricCollection does not recognize OmegaConf containers as their corresponding Python primitives
  # force the conversion of OmegaConf containers to Python primitives
  _convert_: all
  metrics:
    acc:
      _target_: torchmetrics.Accuracy
      task: multiclass
      num_classes: 10
