name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  run_tests_ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # It is considered best practice (by uv's developers) to pin to a specific uv version
          # https://docs.astral.sh/uv/guides/integration/github/#installation
          version: "0.5.11"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --extra cpu

      - name: Run pytest
        run: uv run pytest -v

  # upload code coverage report
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # It is considered best practice (by uv's developers) to pin to a specific uv version
          # https://docs.astral.sh/uv/guides/integration/github/#installation
          version: "0.5.11"

      - name: Set up Python
        run: uv python install

      - name: Install the project + pytest-cov
        run: |
          uv sync --extra cpu
          uv pip install pytest-cov

      - name: Run tests and collect coverage
        run: uv run pytest --cov src # NEEDS TO BE UPDATED WHEN CHANGING THE NAME OF "src" FOLDER

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
